INSERT INTO minor (`minor_id`, `minor_name`, `max_students`)
VALUES (1, 'Applied chemistry and molecular engineering', 50),
       (2, 'Biomechanics', 50),
       (3, 'Biomedical engineering', 50),
       (4, 'Connected systems', 50),
       (5, 'Crime and security engineering', 50),
       (6, 'Engineering & public policy', 50),
       (7, 'Entrepreneurship', 50),
       (8, 'Environmental engineering', 50),
       (9, 'Finance & accounting', 50),
       (10, 'Intelligent systems', 50),
       (11, 'Management', 50),
       (12, 'Manufacturing the future: regenerative medicines', 50),
       (13, 'Modern applications of engineering mathematics', 50),
       (14, 'Modern foreign languages', 50),
       (15, 'Nanotechnology', 50),
       (16, 'Ocean engineering', 50),
       (17, 'Programming', 50),
       (18, 'Strategic thinking in engineering & technology', 50),
       (19, 'Applied chemistry and molecular engineering', 50),
       (20, 'Biomechanics', 50),
       (21, 'Biomedical engineering', 50),
       (22, 'Connected systems', 50),
       (23, 'Crime and security engineering', 50),
       (24, 'Engineering & public policy', 50),
       (25, 'Entrepreneurship', 50),
       (26, 'Environmental engineering', 50),
       (27, 'Finance & accounting', 50),
       (28, 'Intelligent systems', 50),
       (29, 'Management', 50),
       (30, 'Manufacturing the future: regenerative medicines', 50),
       (31, 'Modern applications of engineering mathematics', 50),
       (32, 'Modern foreign languages', 50),
       (33, 'Nanotechnology', 50),
       (34, 'Ocean engineering', 50),
       (35, 'Programming', 50),
       (36, 'Strategic thinking in engineering & technology', 50),
       (37, 'Applied chemistry and molecular engineering', 50),
       (38, 'Biomechanics', 50),
       (39, 'Biomedical engineering', 50),
       (40, 'Connected systems', 50),
       (41, 'Crime and security engineering', 50),
       (42, 'Engineering & public policy', 50),
       (43, 'Entrepreneurship', 50),
       (44, 'Environmental engineering', 50),
       (45, 'Finance & accounting', 50),
       (46, 'Intelligent systems', 50),
       (47, 'Management', 50),
       (48, 'Manufacturing the future: regenerative medicines', 50),
       (49, 'Modern applications of engineering mathematics', 50),
       (50, 'Modern foreign languages', 50),
       (51, 'Nanotechnology', 50),
       (52, 'Ocean engineering', 50),
       (53, 'Programming', 50),
       (54, 'Strategic thinking in engineering & technology', 50);


INSERT INTO programme (`prog_id`, `programme_name`)
VALUES (1, 'BEng Engineering (Biochemical)'),
       (2, 'MEng Engineering (Biochemical)'),
       (3, 'BEng Engineering (Biomedical)'),
       (4, 'MEng Engineering (Biomedical)'),
       (5, 'BEng Engineering (Chemical)'),
       (6, 'MEng Engineering (Chemical)'),
       (7, 'BEng Engineering (Civil)'),
       (8, 'MEng Engineering (Civil)'),
       (9, 'BSc Computer Science'),
       (10, 'MEng Computer Science'),
       (11, 'BEng Engineering (Electronic and Electrical)'),
       (12, 'MEng Engineering (Electronic and Electrical)'),
       (13, 'BSc Management Science'),
       (14, 'MSci Management Science'),
       (15, 'BEng Engineering (Mechanical)'),
       (16, 'MEng Engineering (Mechanical)');

